version: "3.8"

services:
  postgres:
    image: postgres:13-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD:
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./docker/local/Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - postgres
